ppwki/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, include, re_path


import story4.urls as story4
import story6.urls as story6
import story9.urls as story9
import story8.urls as story8


from story8.views import *
from story10.views import *
from story9.views import *
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^', include(story4, namespace="story4")),


    re_path(r'^auth/', include('social_django.urls', namespace='social')),

    # path('lab8/', include('story8.urls')),
    
    path('lab9/', include('story9.urls')),
    path('lab10/', include('story10.urls')),

    

    re_path(r'^lab10$', lab10, name='lab10'),
    path('valid', valid, name="valid"),
    path('post', post, name="post"),

    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^auth/', include('social_django.urls', namespace='social')),


]

story4/urls.py
from django.conf.urls import url
from .views import index1
from .views import register
from .views import about
from .views import contacts
from .views import education
from .views import scheduling
from .views import add_schedule
from .views import show
from .views import erase

app_name = 'story4'

#url for app
urlpatterns = [
    url(r'^$', index1, name='index1'),
    url(r'register/$', register, name='register'),
    url(r'about/$', about , name='about' ),
    url(r'contacts/$', contacts, name='contacts' ),

    url(r'education/$', education, name='education'),
    url(r'scheduling/$', scheduling, name='scheduling'),
    url(r'add_schedule/$', add_schedule, name='add_schedule'),
    url(r'show/$', show, name='show'),
    url(r'erase/$', erase, name='erase')

]

story4/models.py
from django.db import models
from django.utils import timezone

# Create your models here

class Schedule(models.Model):
    activity = models.CharField(max_length=200)
    datetime = models.DateField()
    time = models.TimeField()
    locations = models.CharField(max_length=200)
    category = models.CharField(max_length=200)

story4/forms.py
from django import forms
from django.utils import timezone

class Forms(forms.Form):
    activity_attrs = { 
        "type":"text",
        "placeholder":"Activity Name",
        "name":"activity",
        "value":"",
    }
    calendar_attrs = {
        "type":"date",
        "name":"datetime",
        "value":"",
    }
    locations_attrs = {
        "type":"text",
        "placeholder":"Location",
        "name":"location",
        "value":"",
    }
    category_attrs = {
        "type":"text",
        "placeholder":"Category",
        "name":"category",
        "value":"",
    }
    time_attrs = {
        "type":"time",
        "name":"time",
        "value":"",
    }
    activity = forms.CharField(max_length=200, required = True, widget=forms.TextInput(attrs=activity_attrs))
    datetime = forms.DateField(initial=timezone.now, required = True, widget=forms.DateInput(attrs=calendar_attrs))
    time = forms.TimeField(initial=timezone.now, required=True,widget=forms.TimeInput(attrs=time_attrs))
    locations = forms.CharField(max_length=200, required = True,widget=forms.TextInput(attrs=locations_attrs))
    category = forms.CharField(max_length=200, required = True,widget=forms.TextInput(attrs=category_attrs))

story4/views.py
from django.shortcuts import render
from .forms import Forms
from .models import Schedule
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
response = {}
def index1(request):
    return render(request, 'middle.html', response)

def register(request):
    return render(request, 'register.html')

def about(request):
    return render(request, 'aboutus.html')

def contacts(request):
    return render(request, 'contacts.html')

def education(request):
    return render(request, 'education.html')

def scheduling(request):
	response = {'schedule_form' : Forms	}
	return render(request, "calendar.html", response)

def add_schedule(request):
	forms = Forms(request.POST)
	if(request.method == 'POST'):
		if(forms.is_valid()):
			clean = forms.cleaned_data
			schedule = Schedule()
			schedule.activity = clean['activity']
			schedule.datetime = clean['datetime']
			schedule.locations = clean['locations']
			schedule.category = clean['category']
			schedule.time = clean['time']
			schedule.save()
			return HttpResponseRedirect(reverse('story4:show'))

def show(request):
	response = {
	'schedule' : Schedule.objects.all()
	}
	return render(request,"showschedule.html",response)

def erase(request):
	Schedule.objects.all().delete()
	return HttpResponseRedirect(reverse('story4:show'))

story4/templates/aboutus.html
<html>
{% load staticfiles %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/indexstyle.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Rizal Alfaridzi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'story4:index1' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story4:register' %}">Sign Up</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="firstpage">
        <div class="borderfirstpage">
            <img src="https://i.imgur.com/wnAwxmM.png" width="96" height="95">
        </div>

        <div class="text1">
            <p id="aboutme" class="textprofile" style="font-size: 20px">My name is Muhammad Rizal Alfaridzi, a student
                who is currently
                pursuing a degree in Computer Science at University of Indonesia
                who likes to spend his time during end of the week playing games and hanging out together with his
                friends and also not mention to spare his time with his family.

            </p>
            <p style="font-size: 20px">
                I am currently living in Depok, West Java. Which is pretty near to my campus as long there is no
                traffic jam
            </p>
            <p style="font-size: 20px"> My motto is "be a voice not an echo" -Nardiena, quoted from another person</p>

            <p></p>
        </div>
    </div>
</body>

</html>

story4/templates/calendar.html
{% extends "index1.html" %}
{% block content %}
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
        <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    <title>
        Create Your Schedule !
    </title>
    <body>
        <div class="regisbox">
            <h1>
                Create Your Schedule !
            </h1>
            {% comment %} {{schedule_form.as_p}} {% endcomment %}

            <form method="POST" action="{% url 'story4:add_schedule' %}">
            {% csrf_token %}
            <div class="textbox">
                <i class="fas fa-plane-departure"></i>
                {{schedule_form.activity}}
                {% comment %} <input type="text" placeholder="Activity Name" name="activity" value="" required> {% endcomment %}
            </div>
            <div class="textbox">
                <i class="far fa-calendar"></i>
                {{schedule_form.datetime}}
                {% comment %} <input type="datetime-local" name="datetime" value=""> {% endcomment %}
            </div>
            <div class="textbox">
                <i class="far fa-clock"></i>
                {{schedule_form.time}}
            </div>
            <div class="textbox">
                <i class="fas fa-map-marker-alt"></i>
                {{schedule_form.locations}}
                {% comment %} <input type="text" name="location" value="" placeholder="Location" required> {% endcomment %}
            </div>
            <div class="textbox">
                <i class="fas fa-exclamation"></i>
                {{schedule_form.category}}
                {% comment %} <input type="text" placeholder="Category" name="category" value="" required> {% endcomment %}
            </div>
        <button class="btn btn-outline-secondary btn-lg " aria-pressed="true" style="padding-top:3px;" type="submit">Register</a>
        </div>
    </form>
    </body>
    
</html>
{% endblock %}

story4/templates/contacts.html
<html>
{% load staticfiles %}

<head>
    <link rel="stylesheet" href="{% static '/css/indexstyle.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Rizal Alfaridzi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'story4:index1' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story4:register' %}">Sign Up</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="firstpage">
        <div class="borderfirstpage">
            <img src="https://i.imgur.com/7Srhivv.png" width="96" height="95">
        </div>

        <div class="text1">
            <p id="contacts" class="textprofile" style="font-size: 30px ; margin-bottom: 10rem">
                for further information about me, you can reach me at:
            </p>

            <p style="font-size: 20px ; margin-bottom: 5rem">Whatsapp : 082210512781</p>
            <p style="font-size: 20px ; margin-bottom: 5rem">LINE : rzlalfrdzi</p>
            <p style="font-size: 20px ; margin-bottom: 5rem">Instagram : rzlalfrdzi</p>
        </div>
    </div>

</body>

</html>

story4/templates/education.html
<html>
{% load staticfiles %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/indexstyle.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Rizal Alfaridzi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'story4:index1' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story4:register' %}">Sign Up</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    
    <div class="firstpage">
        <div class="borderfirstpage">
            <img src="http://www.vorderzelg.ch/wp-content/uploads/2017/03/fav.png" width="96" height="95">
        </div>

        <div class="text1">
            <p style="font-size:20px ; margin-bottom: 5rem">My Education Background and Commitee : </p>
            <p id="edu" class="textprofile" style="margin-bottom: 4rem ; font-size: 20px">
                High School : SMA Islam Terpadu Nurul Fikri
            </p>

            <p style="margin-bottom: 4rem ; font-size: 20px">College : University of Indonesia</p>

            <p style="margin-bottom: 5rem ; font-size: 20px">--------------------------------------------------------</p>

            <p style="margin-bottom: 4rem ; font-size: 20px">COMPFEST X 2018 : STAFF OF STAGE DIVISION</p>

            <p style="font-size: 20px">Open House Fasilkom UI 2018 : STAFF OF THE EVENT DIVISION</p>

        </div>
</body>

</html>

story4/templates/index1.html
<!DOCTYPE html>

{% load staticfiles %}

<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/indexstyle.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>

<body>
    <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="#">Rizal Alfaridzi</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
            
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'story4:index1' %}">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'story4:register' %}">Sign Up</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'story4:scheduling' %}">Schedule</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'story4:erase' %}">erase project</a>
                            </li>
                        </ul>
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </div>
                </nav>

    </header>
    <content>
        {% block content %}
        {% endblock %}
    </content>
</body>

</html>

story4/templates/middle.html
{% extends "index1.html" %}
{% block content %}
{% load staticfiles %}

<div class="row">
        <div></div>
        <div class="profpic" ; padding: 3rem>
            <img src="https://i.imgur.com/l0tEg2H.jpg"  class="image--cover">
        </div>
    </div>
    <div id="nama-atas" align="center" class="nama">
        <p>Muhammad Rizal Alfaridzi</p>
    </div>
    <div id="main" class="main">
        <a class="iconhome" href="{% url 'story4:about' %}"><img type="image" src="https://i.imgur.com/Gpvcv9U.png"
                width="72px" height="75px" href="#"></a>

        <a class="iconhome" href="{% url 'story4:contacts' %}"><img type="image" src="https://i.imgur.com/j2Sn4wN.png"
                width="72px" height="75px"></a>

        <a class="iconhome" href="{% url 'story4:education' %}"><img type="image" src="https://i.imgur.com/QY869nI.png"
                width="75px" height="75px"></a>
    </div>

{% endblock %}

story4/templates/register.html
<html>
{% load staticfiles %}

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/css/register.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
        crossorigin="anonymous">
</head>
<title>
    Sign Up
</title>

<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Rizal Alfaridzi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'story4:index1' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story4:register' %}">Sign Up</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="regisbox">
        <h1>
            Register
        </h1>
        <div class="textbox">
            <i class="far fa-user"></i>
            <input type="text" placeholder="Name" name="" value="">
        </div>
        <div class="textbox">
            <i class="far fa-calendar"></i>
            <input type="date" name="" value="">
        </div>
        <div class="textbox">
            <i class="far fa-envelope"></i>
            <input type="email" name="" value="" placeholder="Email">
        </div>
        <div class="textbox">
            <i class="fas fa-at"></i>
            <input type="text" placeholder="Username" name="" value="">
        </div>
        <div class="textbox">
            <i class="fas fa-key"></i>
            <input type="password" placeholder="Password" name="" value="">
        </div>
        <div class="textbox">
            <i class="fas fa-unlock"></i>
            <input type="password" placeholder="Retype Password" name="" value="">
        </div>
        <a href="#" class="btn btn-outline-secondary btn-lg " role="button" aria-pressed="true" style="padding-top:3px;">Regsiter</a>
    </div>
</body>

</html>

story4/templates/showschedule.html
{% extends "index1.html" %} {% block content %} {% load staticfiles %}

<head> 
<title> Your Schedule</title>
<link rel="stylesheet" href="{% static 'css/background.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
<div style="padding: 100px;">
<h1> MY SCHEDULE </h1>
<div style="margin-top:34px;">
{% for item in schedule %}
    <div class="card shadow" style="width: 18rem; border-radius: 32px; padding:15px; margin-bottom:32px;">
        <div class="card-body">
            <h2 class="card-title">    {{item.activity}} </h3>
            <h4 class="card-subtitle mb-2 text-muted">{{item.datetime}}<br>
            <i class="fas fa-map-marker-alt"></i> {{item.locations}} <br>
            <i class="far fa-clock"></i>{{item.time}} <br>
            <i class="fas fa-exclamation"></i> {{item.category}}
            </h5> 
    {% comment %} <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a> {% endcomment %}
        </div>
    </div>
{% endfor %}
</div>
</div>

</body>

{% endblock %}